document.addEventListener('DOMContentLoaded', async () => {
    // Note: Get a free API key from gnews.io or newsapi.org
    const NEWS_API_KEY = CONFIG.NEWS_API_KEY; 
    const newsGrid = document.getElementById('news-grid');
    const loader = document.getElementById('news-loader');
    const filterBtns = document.querySelectorAll('.filter-btn');
    
    const sb = getSupabase();
    let personalTopic = 'general health wellness';

    // 1. Fetch User Data for Personalization
    async function getPersonalizedTopic() {
        const { data: { session } } = await sb.auth.getSession();
        if (session) {
            const { data: profile } = await sb.from('profiles').select('health_status').eq('id', session.user.id).single();
            if (profile?.health_status?.summary) {
                // Extract keywords from the user's health status summary generated by the chatbot
                const summary = profile.health_status.summary.toLowerCase();
                if (summary.includes('diabetes') || summary.includes('blood sugar')) personalTopic = 'diabetes management';
                else if (summary.includes('heart') || summary.includes('pressure')) personalTopic = 'cardiovascular health';
                else if (summary.includes('anxiety') || summary.includes('depression')) personalTopic = 'mental health therapy';
                else if (summary.includes('fitness') || summary.includes('wellness')) personalTopic = 'fitness and nutrition';
            }
        }
        return personalTopic;
    }

    // 2. Fetch News from API
    async function fetchNews(query) {
        newsGrid.innerHTML = '';
        loader.style.display = 'block';

        let searchQuery = query === 'For You' ? await getPersonalizedTopic() : `${query} health`;
        
        // Check cache first to save API quota
        const today = new Date().toISOString().split('T')[0];
        const cacheKey = `gnews_cache_${searchQuery}`;
        const cachedData = localStorage.getItem(cacheKey);
        
        if (cachedData) {
            try {
                const parsedCache = JSON.parse(cachedData);
                if (parsedCache.date === today) {
                    loader.style.display = 'none';
                    if (parsedCache.articles && parsedCache.articles.length > 0) {
                        renderNews(parsedCache.articles);
                    } else {
                        newsGrid.innerHTML = '<p class="empty-state">No news articles found for this topic today.</p>';
                    }
                    return; // Exit early, use cached data
                }
            } catch (e) {
                console.error("Cache parsing error:", e);
            }
        }
        
        // Using GNews API (free tier allows browser requests)
        const url = `https://gnews.io/api/v4/search?q=${encodeURIComponent(searchQuery)}&lang=en&max=9&apikey=${NEWS_API_KEY}`;

        try {
            const response = await fetch(url);
            const data = await response.json();
            
            loader.style.display = 'none';
            
            if (data.articles) {
                try {
                    localStorage.setItem(cacheKey, JSON.stringify({
                        date: today,
                        articles: data.articles
                    }));
                } catch(e) {} // Ignore if quota exceeded on localstorage
            }

            if (data.articles && data.articles.length > 0) {
                renderNews(data.articles);
            } else {
                newsGrid.innerHTML = '<p class="empty-state">No news articles found for this topic today.</p>';
            }
        } catch (error) {
            loader.style.display = 'none';
            newsGrid.innerHTML = '<p class="error-msg" style="grid-column: 1/-1; text-align:center;">Failed to load live news. Please check your API key.</p>';
            console.error("Error fetching news:", error);
        }
    }

    // 3. Render Cards
    function renderNews(articles) {
        articles.forEach(article => {
            const date = new Date(article.publishedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
            const image = article.image || 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=400&q=80'; // Fallback medical image

            const card = document.createElement('a');
            card.className = 'news-card';
            card.href = article.url;
            card.target = '_blank';
            card.innerHTML = `
                <img src="${image}" alt="News Image" class="news-img" loading="lazy">
                <div class="news-content">
                    <span class="news-source">${article.source.name} • ${date}</span>
                    <h3 class="news-title">${article.title}</h3>
                    <p class="news-snippet">${article.description.substring(0, 100)}...</p>
                    <div class="news-footer">
                        Read Article <span class="material-symbols-rounded">arrow_forward</span>
                    </div>
                </div>
            `;
            newsGrid.appendChild(card);
        });
    }

    // 4. Handle Filters
    filterBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            filterBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            fetchNews(btn.dataset.query);
        });
    });

    // Initialize
    fetchNews('For You');
});
